// <auto-generated />
using ManagerSalesTestProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManagerSalesTestProject.Migrations
{
    [DbContext(typeof(ManagerSalesTestProjectContext))]
    [Migration("20250715081628_updateMigration")]
    partial class updateMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManagerSalesTestProject.Models.EquipmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Equipment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HP LaserJet Pro M404n",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Epson WorkForce DS-530",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dell UltraSharp U2720Q",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Canon imageFORMULA DR-C240",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "LG 27UN880-B",
                            Status = 1,
                            Type = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
